local keymap  = vim.keymap

keymap.set('n', 'te', ':tabnew<CR>')
keymap.set("n", 'K', ":Lspsaga hover_doc<CR>")
keymap.set('n', '<C-j>', ':Lspsaga diagnostic_jump_next<CR>')
keymap.set('n', '<C-p>', ':Lspsaga diagnostic_jump_prev<CR>')
keymap.set('n', 'lf', ':Lspsaga finder<CR>')
keymap.set('n', '<Tab>', ':tabnext<CR>')
keymap.set('n', '<S-Tab>', ':tabprev<CR>')
keymap.set('n', 'qf', ':Prettier<CR>')
keymap.set('n', 'sf', ':Telescope file_browser<CR>')
keymap.set({'n', 't'}, 'tt', ":Lspsaga term_toggle<CR>")
keymap.set({'n', 't'}, 'gr', ":Lspsaga rename<CR>")
keymap.set('n', 'ca', ':Lspsaga code_action<CR>')
keymap.set('n', 'oo', ':Lspsaga outline<CR>')
